# Generated by Django 4.0.3 on 2022-04-06 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metagram', '0003_profile_images_comments_images_likes_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='images',
            name='likes',
        ),
    ]
